#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid and displays:
# - 'To infinity and beyond' indefinitely
# - 'I hate the kill command' when receiving a SIGINT signal
# - 'Y U no love me?!' when receiving a SIGINT signal
# It also deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal
kill_script() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && kill_script' SIGTERM
	trap 'kill_script' SIGQUIT
done
