#!/usr/bin/env bash
# This script that indefinitely writes 'I am alive!' to /tmp/my_process
# In between every message, the program pauses for 2 seconds
while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
