#!/usr/bin/env bash
# This script displays the contents of the file etc/passwd
# It displays the username, user id and home directory path
while read -r pwd; do
	echo "$pwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
